// Generated by CoffeeScript 1.10.0

/*
 http://hitokoto.us/
 简单来说，一言（ヒトコト）指的是就是一句话，可以是动漫中的台词，可以是小说中的语句，也可以是网络上的各种小段子。
 或是感动，或是开心，又或是单纯的回忆，来到这里，留下你所喜欢的那一句句话，与大家分享，这就是一言存在的目的。
 */

(function() {
  module.exports = function(content, send, robot, message) {
    var client = require('../src/httpclient');
    var ret = content.match(/^comic\s+(.*)/i);
    if (ret) {
      return client.post({
            url: "http://www.niurenqushi.com/api/simsimi/",
            json: true
          },
          {
            txt: ret[1]
          }
          , function(data) {
            console.log(data);
            if (data && data.text){
              send(data.text);
            }else{
              send("我伙呆["+JSON.stringify(data)+"]");
            }
          });
    }
  };

}).call(this);
